spring:
  datasource:
    url: ${db.dev.money.server}?autoReconnect=true&useSSL=false
    username: ${db.dev.money.user}
    password: ${db.dev.money.password}

  boot:
    admin:
      client:
        url: ${spring.admin.clienturl}

  application:
    name: Middle Tier Podcast (Development)

  h2:
    console:
      enabled: false

logging.file: /var/log/jbr/MiddleTier-Podcast-DEV.log
logging:
  file:
    max-history: 3
    max-size: 100MB

server:
  port: 10009

money:
  service-name: "Middle Tier Development"

info:
  app:
    version: Development
